### ISSUE TITLE
Error in err[c(1, 6, 11, 16), ] <- 1 :   incorrect number of subscripts on matrix

### ISSUE THREAD

**Issue by yjiakang** [benjjneb/dada2#1342]
Hi, I encountered an error when running dada2 plugin in the qiime2-2019.7, can you help with the following info？ Thanks in advance.
```
running dada2 ...
Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_dada_paired.R /tmp/tmpui69c8hs/forward /tmp/tmpui69c8hs/reverse /tmp/tmpui69c8hs/output.tsv.biom /tmp/tmpui69c8hs/track.tsv /tmp/tmpui69c8hs/filt_f /tmp/tmpui69c8hs/filt_r 0 0 0 0 2.0 2.0 2 consensus 1.0 1 1000000

R version 3.5.1 (2018-07-02)
Loading required package: Rcpp
DADA2: 1.10.0 / Rcpp: 1.0.2 / RcppParallel: 4.4.3
1) Filtering ...
2) Learning Error Rates
70907162 total bases in 291823 reads from 3 samples will be used for learning the error rates.
73233596 total bases in 291823 reads from 3 samples will be used for learning the error rates.
Error in err[c(1, 6, 11, 16), ] <- 1 :
  incorrect number of subscripts on matrix
Execution halted
Traceback (most recent call last):
  File "/home/yjk/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 234, in denoise_paired
    run_commands([cmd])
  File "/home/yjk/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 36, in run_commands
    subprocess.run(cmd, check=True)
  File "/home/yjk/miniconda3/envs/qiime2-2019.7/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_dada_paired.R', '/tmp/tmpui69c8hs/forward', '/tmp/tmpui69c8hs/reverse', '/tmp/tmpui69c8hs/output.tsv.biom', '/tmp/tmpui69c8hs/track.tsv', '/tmp/tmpui69c8hs/filt_f', '/tmp/tmpui69c8hs/filt_r', '0', '0', '0', '0', '2.0', '2.0', '2', 'consensus', '1.0', '1', '1000000']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yjk/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/commands.py", line 327, in __call__
    results = action(**arguments)
  File "</home/yjk/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/decorator.py:decorator-gen-459>", line 2, in denoise_paired
  File "/home/yjk/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable
    output_types, provenance)
  File "/home/yjk/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 383, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/yjk/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 249, in denoise_paired
    " and stderr to learn more." % e.returncode)
Exception: An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

Plugin error from dada2:

  An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

See above for debug info.
```

**Comment by benjjneb** [comment]
For issues with the Q2 plugin, it is recommended to get help through the QIIME2 forum: https://forum.qiime2.org/

It is common that errors with the plugin are more easily idnetified/common there, than they are here where we support the R package through the R interface.
