### ISSUE TITLE
cutadapt in ITS workflow

### ISSUE THREAD

**Issue by cpavloud** [benjjneb/dada2#832]
Hi!

I seem to be getting an error when running cutadapt.

After the command 
`
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, 
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], 
                             fnFs.filtN[i], fnRs.filtN[i]))
}
`

I get the message below
`
This is cutadapt 1.12 with Python 3.5.3
Command line parameters: -g CTTGGTCATTTAGAGGAAGTAA -a GCATCGATGAAGAACGCAGC -G GCTGCGTTCTTCATCGATGC -A TTACTTCCTCTAAATGACCAAG -n 2 -o /mnt/scratch/christina/ITS/cutadapt/ARMS-ITS-1_S124_L001_R1_001.fastq -p /mnt/scratch/christina/ITS/cutadapt/ARMS-ITS-1_S124_L001_R2_001.fastq /mnt/scratch/christina/ITS/filtN/ARMS-ITS-1_S124_L001_R1_001.fastq /mnt/scratch/christina/ITS/filtN/ARMS-ITS-1_S124_L001_R2_001.fastq
Trimming 4 adapters with at most 10.0% errors in paired-end mode ...
Traceback (most recent call last):
  File "/usr/bin/cutadapt", line 11, in <module>
    load_entry_point('cutadapt==1.12', 'console_scripts', 'cutadapt')()
  File "/usr/lib/python3/dist-packages/cutadapt/scripts/cutadapt.py", line 707, in main
    stats = pipeline.run()
  File "/usr/lib/python3/dist-packages/cutadapt/scripts/cutadapt.py", line 140, in run
    for read1, read2 in self.paired_reader:
  File "/usr/lib/python3/dist-packages/cutadapt/seqio.py", line 397, in __iter__
    r1 = next(it1)
  File "cutadapt/_seqio.pyx", line 98, in __iter__ (cutadapt/_seqio.c:2752)
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
`

And all the files in the cutadapt folder are actually empty. 
(FYI: I am using R version 3.5.2, dada2 version 1.10.1, ShortRead version 1.40.0, Biostrings version 2.50.2.

**Comment by cpavloud** [comment]
No, my files are not compressed...
They are .fastq

**Comment by cpavloud** [comment]
I am following the ITS tutorial but I am starting with uncompressed files. 
`
# Forward and reverse fastq filenames
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))
`
But you are correct.
Somehow the files in my filtN/ directory (which are .fastq) look like nonsense when I open them...

I compressed my raw files, I am re-running the tutorial and cutadapt is working. 

Thank you!
